name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true  # If you're using themes as submodules
          fetch-depth: 0    # Fetch all history for all branches

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build Site
        run: |
          hugo --minify  # Build the static files
          ls -la public/  # List the contents of the public folder to verify

      - name: Create gh-pages branch if it doesn't exist
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if ! git show-ref --quiet refs/heads/gh-pages; then
            git checkout --orphan gh-pages  # Create the branch if it doesn't exist
            git rm -rf .                    # Remove all files
            echo "# Placeholder for gh-pages" > README.md
            git add README.md
            git commit -m "Initial gh-pages branch"
            git push origin gh-pages --force
          else
            git checkout gh-pages  # Checkout if it exists
          fi

      - name: Deploy to GitHub Pages
        run: |
          git rm -rf .  # Clear the gh-pages branch
          cp -R public/* .  # Copy new files from public
          git add .
          git commit -m "Deploy updated site"
          git push origin gh-pages
